### ISSUE TITLE
Function missing 

### ISSUE THREAD

**Issue by plotnicsystems** [wisp-gg/whmcs#6]
some functions are missing, e.g. start, stop, restart etc. we will update the module soon and provide the missing functions.

**Comment by TrixterTheTux** [comment]
This is on purpose, as having such features doesn't make much sense inside of the module. For example, if the user was able to start the game server from the billing panel, that would be mostly meaningless due to not being able to see the server state or what is happening with it, and reinventing the game panel UI into WHMCS isn't the goal as that basically requires twice amount of work for any changes to the game panel (vs. just opening the game panel).
